import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { LanguageProvider } from "@/providers/LanguageProvider";
import { MainNavbar } from "@/components/shared/Navbar";
import { LanguageSwitcher } from "@/components/shared/LanguageSwitcher";
import "@/i18n/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-white dark:bg-slate-500`}
      >
        <ThemeProvider>
          <LanguageProvider>
            <MainNavbar />
            {children}
            <footer className="fixed bottom-4 right-4">
              <LanguageSwitcher />
            </footer>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
